---
- name: Configure webserver with nginx and tls
  hosts: webservers 
  sudo:  True
  vars:
     key_file: /etc/nginx/ssl/nginx.key
     cert_file: /etc/nginx/ssl/nginx.crt
     conf_file: /etc/nginx/nginx.conf
     server_name: localhost
  roles:
    - common
  tasks:
    - name:  Install EPEL release for nginx
      yum: name=epel-release state=present

    - name: install nginx
      yum: name=nginx state=present update_cache=true
      notify: restart nginx 

    - name: copy TLS key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: Copy TLS Certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

  handlers:
    - name: restart nginx
      service: name=nginx enabled=yes state=restarted
