---
# For this to work correctly port 80 must be open
# 
- name: Configure webserver with nginx
  hosts: webservers 
  sudo:  True
  roles:
    - common
  tasks:
    - name:  Install EPEL release for nginx
      yum: name=epel-release state=present

    - name: install nginx
      yum: name=nginx state=present update_cache=true
      notify:
         - start nginx 

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

    - name: copy index.html
      copy: src=files/index.html dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx enabled=yes state=restarted
