---
- name: Configure webserver with nginx and tls
  hosts: webservers 
  sudo:  True
  vars:
     key_file: /etc/pki/tls/certs/server.key
     cert_file: /etc/pki/tls/certs/server.crt
     conf_file: /etc/nginx/conf.d/default.conf
     server_name: 10.211.55.16
  roles:
    - common
  tasks:
    - name:  Install EPEL release for nginx
      yum: name=epel-release state=present

    - name: install nginx
      yum: name=nginx state=present update_cache=true
      notify: 
      - restart nginx 

    - name: copy nginx config file
      template: src=templates/ssl.conf.j2 dest=/etc/nginx/conf.d/default.conf
      notify:
      - restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

  handlers:
    - name: restart nginx
      service: name=nginx enabled=yes state=restarted
