---
-  name:  install yum packages for postgres
   yum: name={{ item }} update_cache=true state=present
   sudo: True
   with_items:
     - postgresql-libs
     - postgresql-server
     # Adapter fort Python programming language
     - python-psycopg2
   
